In [27]:
from sklearn.linear_model import SGDClassifier
import numpy as np

## Client Update


In [28]:
def client_update(init_weights, epochs, batch_size, features, labels):
    """
    Given the previous weights from the server, it does updates on the model
    and returns the new set of weights

    init_weights: weights to initialize the training with 
        ex: [coef1, coef2, ..., coefn, intercept]
    epochs: number of epochs to run the training for 
    batch_size: the size of each batch of data while training 
    features: a 2D array containing features for each sample 
        ex: [[feature1, feature2], [feature1, feature2], ...]
    label: an array containing the labels for the corresponding sample in "features"
        ex: [label1, label2, ...]
    """
    
    # split the data into batches by given batch_size
    # TODO: need to ensure that a batch doesn't just contain 1 label
    batches_features = []
    batches_labels = []
    
    for i in range(0, len(features), batch_size):
      batches_features.append(features[i:i + batch_size])
      batches_labels.append(labels[i:i + batch_size])
      # TODO: merge the features and labels into one tuple?
    
    print("Features: ", batches_features)
    print("Labels: ", batches_labels)

    weights = list(init_weights)
    
    # set max_iter to 1 so that each .fit() call only does one training step
    classifier = SGDClassifier(loss="hinge", penalty="l2", max_iter=1)

    for epoch in range(epochs):
        for i in range(len(batches_features)):
            print(batches_features[i], batches_labels[i], weights)
            
            classifier.fit(batches_features[i],
                           batches_labels[i],
                           coef_init=weights[:-1],
                           intercept_init=weights[-1])
            
            # update the weights so for the next batch the new ones are used
            weights = np.append(classifier.coef_[0], classifier.intercept_)
            
    return weights

# Example usage

# this data will be provided by the server
features = [[1, 4, 3], [0, 2, 2], [1, 4, 0], [0, 5, 3], [1, 2, 1], [0, 2, 9]]
labels = [1, 0, 1, 0, 1, 0]
weights = [29., 0., 0., -9]
epochs = 3
batch_size = 3

new_weights = client_update(weights, epochs, batch_size, features, labels)
print(new_weights)

Features:  [[[1, 4, 3], [0, 2, 2], [1, 4, 0]], [[0, 5, 3], [1, 2, 1], [0, 2, 9]]]
Labels:  [[1, 0, 1], [0, 1, 0]]
[[1, 4, 3], [0, 2, 2], [1, 4, 0]] [1, 0, 1] [29.0, 0.0, 0.0, -9]
[[0, 5, 3], [1, 2, 1], [0, 2, 9]] [0, 1, 0] [28.91317365  0.          0.         -9.        ]
[[1, 4, 3], [0, 2, 2], [1, 4, 0]] [1, 0, 1] [28.82660726  0.          0.         -9.        ]
[[0, 5, 3], [1, 2, 1], [0, 2, 9]] [0, 1, 0] [28.74030006  0.          0.         -9.        ]
[[1, 4, 3], [0, 2, 2], [1, 4, 0]] [1, 0, 1] [28.65425125  0.          0.         -9.        ]
[[0, 5, 3], [1, 2, 1], [0, 2, 9]] [0, 1, 0] [28.56846008  0.          0.         -9.        ]
[28.48292577  0.          0.         -9.        ]


/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceW

## Server Update

In [29]:
from sklearn.linear_model import SGDClassifier
import random
import numpy as np

def append(list, element):
    """
    helper function to append array into array in numpy
    """
    return np.concatenate((list, [element])) if list is not None else [element]

def server(init_weight,client_num,client_fraction,round_num,features,labels,epoch,batch_size):
    
    """
    Calls clientUpdate to get the updated weights from clients, and applies Federated
    Averaging Algorithm to update the weight on server side
    
    """

    # initialize the weight
    w = init_weight
    # number of clients
    K = client_num
    # fraction of clients
    C = client_fraction

    # use to generate n_k so that the sum of n_k equals to n
    for i in range(round_num):
        # calculate the number of clients used in this round
        m = max(int(K*C),1)
        # random set of m clients
        S = np.array(random.sample(range(clients), clients))
        
        num_samples = []
            
        # grab all the weights from clients
        client_weights = None   
        for i in S:
            client_feature = features[i]
            client_label = labels[i]
            client_weights = append(client_weights,client_update(w,epoch,batch_size,client_feature,client_label))         
            num_samples.append(len(client_feature))

        # calculate the new server weight based on new weights coming from client
        new_w = np.zeros(4)
        for i in range(len(client_weights)):
            current_weight = client_weights[i]
            n_k = len(features[i])
            added_w = [value*(n_k)/sum(num_samples) for value in current_weight]
            new_w = np.add(new_w,added_w)
        
        # update the server weight to newly calculated weight
        w = new_w
        print(w)
        


In [30]:
import numpy as np

# load data

clients = 10
data_number = 30
features = np.random.randint(10,size=(clients,data_number,3))
labels = np.random.randint(2,size=(100,30))
epoch = 10
batch_size = 20

server([0,0,0,0],10,0.5,10,features,labels,epoch,batch_size)

Features:  [array([[7, 6, 4],
       [2, 5, 9],
       [2, 6, 0],
       [0, 3, 8],
       [0, 9, 4],
       [6, 3, 7],
       [8, 8, 9],
       [1, 4, 8],
       [1, 8, 9],
       [9, 2, 8],
       [9, 1, 2],
       [5, 6, 3],
       [3, 9, 3],
       [7, 9, 8],
       [4, 8, 2],
       [8, 9, 5],
       [8, 4, 9],
       [7, 6, 0],
       [5, 4, 5],
       [6, 9, 8]]), array([[2, 9, 5],
       [0, 4, 4],
       [4, 8, 8],
       [8, 3, 4],
       [5, 9, 5],
       [8, 3, 8],
       [0, 9, 7],
       [5, 0, 3],
       [8, 0, 8],
       [1, 0, 4]])]
Labels:  [array([1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0]), array([1, 0, 1, 0, 1, 0, 1, 1, 0, 0])]
[[7 6 4]
 [2 5 9]
 [2 6 0]
 [0 3 8]
 [0 9 4]
 [6 3 7]
 [8 8 9]
 [1 4 8]
 [1 8 9]
 [9 2 8]
 [9 1 2]
 [5 6 3]
 [3 9 3]
 [7 9 8]
 [4 8 2]
 [8 9 5]
 [8 4 9]
 [7 6 0]
 [5 4 5]
 [6 9 8]] [1 1 0 0 1 1 0 1 1 0 1 0 1 1 1 1 0 0 1 0] [0, 0, 0, 0]
[[2 9 5]
 [0 4 4]
 [4 8 8]
 [8 3 4]
 [5 9 5]
 [8 3 8]
 [0 9 7]
 [5 0 3]
 [8 0 8]
 [1 0 4]]

/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceW

 [ 43.80223437  19.31335425 -58.92930022  29.9716917 ]
[[1 2 5]
 [4 4 6]
 [3 6 8]
 [5 0 8]
 [4 5 6]
 [5 2 8]
 [5 3 1]
 [0 9 5]
 [7 9 7]
 [8 3 2]] [1 0 1 1 0 1 0 0 1 1] [ 23.3154388   18.9342894  -97.02686057  39.93247082]
[[3 1 4]
 [6 1 5]
 [6 2 6]
 [7 0 4]
 [0 9 4]
 [6 7 9]
 [1 5 9]
 [4 2 1]
 [8 7 7]
 [5 9 9]
 [0 1 1]
 [5 5 4]
 [3 7 3]
 [4 7 3]
 [8 9 8]
 [1 5 0]
 [1 0 9]
 [0 5 4]
 [2 0 8]
 [1 4 3]] [1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1 0 0] [ -6.64804424 -10.98577293 -36.60042984  40.04166629]
[[1 2 5]
 [4 4 6]
 [3 6 8]
 [5 0 8]
 [4 5 6]
 [5 2 8]
 [5 3 1]
 [0 9 5]
 [7 9 7]
 [8 3 2]] [1 0 1 1 0 1 0 0 1 1] [ 52.36369363  18.67047384 -55.50915546  40.04351231]
[[3 1 4]
 [6 1 5]
 [6 2 6]
 [7 0 4]
 [0 9 4]
 [6 7 9]
 [1 5 9]
 [4 2 1]
 [8 7 7]
 [5 9 9]
 [0 1 1]
 [5 5 4]
 [3 7 3]
 [4 7 3]
 [8 9 8]
 [1 5 0]
 [1 0 9]
 [0 5 4]
 [2 0 8]
 [1 4 3]] [1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1 0 0] [ 12.20151629 -90.53339607 -25.22660684  30.14285752]
[[1 2 5]
 [4 4 6]
 [3 6 8]
 [5 0 8]
 [4 5 6]
 [5 2 8]
 [5

/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceW

 [1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1 0 0] [126.88271256 -30.55174656 -15.15913097  30.12344732]
[[1 2 5]
 [4 4 6]
 [3 6 8]
 [5 0 8]
 [4 5 6]
 [5 2 8]
 [5 3 1]
 [0 9 5]
 [7 9 7]
 [8 3 2]] [1 0 1 1 0 1 0 0 1 1] [114.57883204 -20.13856214 -54.11577217  40.1628933 ]
[[3 1 4]
 [6 1 5]
 [6 2 6]
 [7 0 4]
 [0 9 4]
 [6 7 9]
 [1 5 9]
 [4 2 1]
 [8 7 7]
 [5 9 9]
 [0 1 1]
 [5 5 4]
 [3 7 3]
 [4 7 3]
 [8 9 8]
 [1 5 0]
 [1 0 9]
 [0 5 4]
 [2 0 8]
 [1 4 3]] [1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1 0 0] [ 24.24603886 -59.58218392 -53.57944143  30.22245698]
[[1 2 5]
 [4 4 6]
 [3 6 8]
 [5 0 8]
 [4 5 6]
 [5 2 8]
 [5 3 1]
 [0 9 5]
 [7 9 7]
 [8 3 2]] [1 0 1 1 0 1 0 0 1 1] [102.27850129  49.53621027 -42.71429047  60.1133167 ]
Features:  [array([[4, 6, 9],
       [5, 6, 4],
       [1, 9, 1],
       [6, 4, 6],
       [9, 3, 2],
       [5, 7, 9],
       [4, 7, 1],
       [6, 9, 9],
       [9, 8, 3],
       [0, 5, 1],
       [1, 9, 7],
       [3, 6, 2],
       [4, 3, 8],
       [3, 3, 9],
       [9, 6, 5],
       [0,

[[4 2 6]
 [5 6 3]
 [2 2 2]
 [6 3 8]
 [6 7 9]
 [5 3 4]
 [1 9 7]
 [1 0 3]
 [8 6 1]
 [7 5 3]] [1 0 0 0 1 1 1 0 1 1] [  42.88465075  -51.62700454    6.69606263 -109.37214839]
[[4 0 3]
 [6 7 7]
 [3 5 4]
 [6 3 9]
 [4 0 8]
 [1 4 0]
 [4 6 4]
 [1 8 2]
 [0 3 4]
 [7 4 6]
 [3 7 3]
 [2 2 9]
 [8 5 2]
 [8 3 1]
 [7 3 1]
 [7 2 9]
 [0 4 7]
 [0 7 0]
 [9 2 9]
 [4 4 7]] [1 1 0 1 0 0 1 0 0 1 1 1 1 1 1 1 1 1 1 0] [  92.01364331  -31.29373393  -23.10270906 -109.35214908]
[[4 2 6]
 [5 6 3]
 [2 2 2]
 [6 3 8]
 [6 7 9]
 [5 3 4]
 [1 9 7]
 [1 0 3]
 [8 6 1]
 [7 5 3]] [1 0 0 0 1 1 1 0 1 1] [  50.95351292  -30.67952915   -3.02218483 -119.11736563]


/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceW

Features:  [array([[5, 2, 5],
       [5, 2, 4],
       [7, 9, 4],
       [5, 6, 6],
       [2, 1, 8],
       [4, 4, 8],
       [6, 7, 6],
       [6, 8, 9],
       [3, 9, 7],
       [2, 4, 4],
       [6, 0, 9],
       [4, 9, 7],
       [5, 9, 8],
       [4, 7, 6],
       [6, 4, 6],
       [9, 6, 2],
       [5, 6, 7],
       [5, 8, 2],
       [3, 9, 7],
       [2, 2, 8]]), array([[4, 1, 4],
       [7, 2, 7],
       [7, 2, 0],
       [5, 6, 5],
       [1, 0, 3],
       [8, 3, 7],
       [6, 4, 3],
       [9, 3, 7],
       [4, 3, 6],
       [3, 1, 7]])]
Labels:  [array([1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0]), array([0, 1, 0, 0, 1, 1, 0, 1, 1, 0])]
[[5 2 5]
 [5 2 4]
 [7 9 4]
 [5 6 6]
 [2 1 8]
 [4 4 8]
 [6 7 6]
 [6 8 9]
 [3 9 7]
 [2 4 4]
 [6 0 9]
 [4 9 7]
 [5 9 8]
 [4 7 6]
 [6 4 6]
 [9 6 2]
 [5 6 7]
 [5 8 2]
 [3 9 7]
 [2 2 8]] [1 1 0 0 1 0 1 1 1 1 0 0 1 0 1 0 0 0 1 0] [0, 0, 0, 0]
[[4 1 4]
 [7 2 7]
 [7 2 0]
 [5 6 5]
 [1 0 3]
 [8 3 7]
 [6 4 3]
 [9 3 7]
 [4 3 6]
 [3 1 7]]

 [8 5 4]] [0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 1 0 0 1 1] [ 15.01261093 -69.57897406 -41.71054895  86.30235323]

/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceW


[[7 1 4]
 [7 0 4]
 [5 0 4]
 [1 3 3]
 [0 9 9]
 [2 9 8]
 [6 9 6]
 [5 5 1]
 [3 5 2]
 [6 3 6]] [1 1 1 0 0 0 0 0 0 0] [-14.72267093  78.98979874 -70.33252051  96.34086447]
[[7 6 7]
 [4 1 8]
 [8 2 3]
 [9 1 9]
 [2 7 1]
 [1 7 2]
 [3 7 2]
 [4 3 3]
 [0 4 3]
 [5 7 4]
 [0 4 7]
 [3 8 3]
 [6 9 5]
 [1 5 0]
 [3 1 7]
 [9 6 0]
 [6 2 7]
 [8 9 8]
 [0 8 8]
 [8 5 4]] [0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 1 0 0 1 1] [ 15.15565088 -60.54429243 -69.63546877  96.38052724]
[[7 1 4]
 [7 0 4]
 [5 0 4]
 [1 3 3]
 [0 9 9]
 [2 9 8]
 [6 9 6]
 [5 5 1]
 [3 5 2]
 [6 3 6]] [1 1 1 0 0 0 0 0 0 0] [ -14.58243844   19.15235708 -136.9635263    96.45922921]
[[7 6 7]
 [4 1 8]
 [8 2 3]
 [9 1 9]
 [2 7 1]
 [1 7 2]
 [3 7 2]
 [4 3 3]
 [0 4 3]
 [5 7 4]
 [0 4 7]
 [3 8 3]
 [6 9 5]
 [1 5 0]
 [3 1 7]
 [9 6 0]
 [6 2 7]
 [8 9 8]
 [0 8 8]
 [8 5 4]] [0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 1 0 0 1 1] [ 54.93770466 -30.59147203 -66.23048838 106.45918939]
[[7 1 4]
 [7 0 4]
 [5 0 4]
 [1 3 3]
 [0 9 9]
 [2 9 8]
 [6 9 6]
 [5 5 1]
 [3 5 2]
 [6 3 6]] [1 1 1 0 0 0 0 0

 [8 6 9]] [0 1 1 1 1 1 1 1 0 1] [   8.40238791  -72.88833648 -117.20147353   79.03602263]


/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceW

[[2 7 3]
 [4 0 0]
 [8 2 8]
 [3 6 1]
 [4 2 6]
 [7 6 2]
 [2 8 4]
 [7 7 8]
 [9 1 6]
 [1 4 6]
 [8 7 2]
 [8 6 1]
 [3 8 5]
 [4 2 4]
 [7 0 6]
 [5 0 9]
 [0 6 7]
 [5 7 3]
 [8 4 5]
 [1 0 7]] [0 1 1 1 0 1 1 1 0 0 0 1 0 1 1 0 0 0 0 1] [ 47.9623246  -62.25515177  52.44373433  98.996182  ]
[[0 6 7]
 [0 1 9]
 [8 0 3]
 [5 1 9]
 [9 2 6]
 [4 0 8]
 [4 5 5]
 [6 7 4]
 [8 9 6]
 [8 6 9]] [0 1 1 1 1 1 1 1 0 1] [ 47.02096396 -41.40617922 -95.78872365  89.06487487]
[[2 7 3]
 [4 0 0]
 [8 2 8]
 [3 6 1]
 [4 2 6]
 [7 6 2]
 [2 8 4]
 [7 7 8]
 [9 1 6]
 [1 4 6]
 [8 7 2]
 [8 6 1]
 [3 8 5]
 [4 2 4]
 [7 0 6]
 [5 0 9]
 [0 6 7]
 [5 7 3]
 [8 4 5]
 [1 0 7]] [0 1 1 1 0 1 1 1 0 0 0 1 0 1 1 0 0 0 0 1] [ 135.75217343 -120.28223294   34.00105557   99.08451935]
[[0 6 7]
 [0 1 9]
 [8 0 3]
 [5 1 9]
 [9 2 6]
 [4 0 8]
 [4 5 5]
 [6 7 4]
 [8 9 6]
 [8 6 9]] [0 1 1 1 1 1 1 1 0 1] [  -4.30184371 -108.1079006   -84.42879832   89.30947015]
[[2 7 3]
 [4 0 0]
 [8 2 8]
 [3 6 1]
 [4 2 6]
 [7 6 2]
 [2 8 4]
 [7 7 8]
 [9 1 6]
 [1 4 6]
 [8 7 2]
 [8 6

/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceW

 [array([0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0]), array([1, 0, 1, 0, 0, 1, 0, 0, 1, 0])]
[[5 1 7]
 [9 8 1]
 [0 1 2]
 [2 9 3]
 [4 4 5]
 [4 7 6]
 [3 6 6]
 [2 0 4]
 [4 7 0]
 [8 6 4]
 [7 6 8]
 [4 5 2]
 [8 5 3]
 [2 1 4]
 [6 5 5]
 [1 4 8]
 [3 6 1]
 [6 0 1]
 [9 0 4]
 [5 7 7]] [0 0 0 1 0 0 1 0 1 0 1 0 0 1 1 1 0 1 0 0] [10.407000083357236, 18.681045069606405, -3.091509150724237, 8.798759296147216]
[[9 5 5]
 [7 3 3]
 [2 0 0]
 [9 8 7]
 [4 2 5]
 [1 4 7]
 [2 6 7]
 [6 9 3]
 [1 4 3]
 [8 0 3]] [1 0 1 0 0 1 0 0 1 0] [-107.55977126   28.12793329   46.03688161   -1.22028094]
[[5 1 7]
 [9 8 1]
 [0 1 2]
 [2 9 3]
 [4 4 5]
 [4 7 6]
 [3 6 6]
 [2 0 4]
 [4 7 0]
 [8 6 4]
 [7 6 8]
 [4 5 2]
 [8 5 3]
 [2 1 4]
 [6 5 5]
 [1 4 8]
 [3 6 1]
 [6 0 1]
 [9 0 4]
 [5 7 7]] [0 0 0 1 0 0 1 0 1 0 1 0 0 1 1 1 0 1 0 0] [-47.02895093  37.75996567  45.58061915   8.74967087]
[[9 5 5]
 [7 3 3]
 [2 0 0]
 [9 8 7]
 [4 2 5]
 [1 4 7]
 [2 6 7]
 [6 9 3]
 [1 4 3]
 [8 0 3]] [1 0 1 0 0 1 0 0 1 0] [-75.54653776 -80.74366467

 [5 7 7]] [0 0 0 1 0 0 1 0 1 0 1 0 0 1 1 1 0 1 0 0] [-42.99941388  42.65851928  42.8273211   57.13531965]
[[9 5 5]
 [7 3 3]
 [2 0 0]
 [9 8 7]
 [4 2 5]
 [1 4 7]
 [2 6 7]
 [6 9 3]
 [1 4 3]
 [8 0 3]] [1 0 1 0 0 1 0 0 1 0] [-51.96900341 -17.05999926 -26.70805321  37.292351  ]
[[5 1 7]
 [9 8 1]
 [0 1 2]
 [2 9 3]
 [4 4 5]
 [4 7 6]
 [3 6 6]
 [2 0 4]
 [4 7 0]
 [8 6 4]
 [7 6 8]
 [4 5 2]
 [8 5 3]
 [2 1 4]
 [6 5 5]
 [1 4 8]
 [3 6 1]
 [6 0 1]
 [9 0 4]
 [5 7 7]] [0 0 0 1 0 0 1 0 1 0 1 0 0 1 1 1 0 1 0 0] [-71.27555441 -66.44493485  -6.62174941  47.30216321]
[[9 5 5]
 [7 3 3]
 [2 0 0]
 [9 8 7]
 [4 2 5]
 [1 4 7]
 [2 6 7]
 [6 9 3]
 [1 4 3]
 [8 0 3]] [1 0 1 0 0 1 0 0 1 0] [-79.69016571 -35.70018637  -6.49178377  47.55703814]
[[5 1 7]
 [9 8 1]
 [0 1 2]
 [2 9 3]
 [4 4 5]
 [4 7 6]
 [3 6 6]
 [2 0 4]
 [4 7 0]
 [8 6 4]
 [7 6 8]
 [4 5 2]
 [8 5 3]
 [2 1 4]
 [6 5 5]
 [1 4 8]
 [3 6 1]
 [6 0 1]
 [9 0 4]
 [5 7 7]] [0 0 0 1 0 0 1 0 1 0 1 0 0 1 1 1 0 1 0 0] [-88.81117497   4.29684224  82.76977999  67.52712717]
[[9 5 

/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceW


[[7 1 4]
 [7 0 4]
 [5 0 4]
 [1 3 3]
 [0 9 9]
 [2 9 8]
 [6 9 6]
 [5 5 1]
 [3 5 2]
 [6 3 6]] [1 1 1 0 0 0 0 0 0 0] [ 30.64363813  60.8621568  -77.30205533   7.74994813]
[[7 6 7]
 [4 1 8]
 [8 2 3]
 [9 1 9]
 [2 7 1]
 [1 7 2]
 [3 7 2]
 [4 3 3]
 [0 4 3]
 [5 7 4]
 [0 4 7]
 [3 8 3]
 [6 9 5]
 [1 5 0]
 [3 1 7]
 [9 6 0]
 [6 2 7]
 [8 9 8]
 [0 8 8]
 [8 5 4]] [0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 1 0 0 1 1] [ 40.25073785 -68.58147211 -66.62512713   7.72011714]
[[7 1 4]
 [7 0 4]
 [5 0 4]
 [1 3 3]
 [0 9 9]
 [2 9 8]
 [6 9 6]
 [5 5 1]
 [3 5 2]
 [6 3 6]] [1 1 1 0 0 0 0 0 0 0] [  0.20656242 -27.98124695 -55.50392738  17.71039879]
[[7 6 7]
 [4 1 8]
 [8 2 3]
 [9 1 9]
 [2 7 1]
 [1 7 2]
 [3 7 2]
 [4 3 3]
 [0 4 3]
 [5 7 4]
 [0 4 7]
 [3 8 3]
 [6 9 5]
 [1 5 0]
 [3 1 7]
 [9 6 0]
 [6 2 7]
 [8 9 8]
 [0 8 8]
 [8 5 4]] [0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 1 0 0 1 1] [ 59.66933187 -47.52553588 -35.13223336  27.65091427]
[[7 1 4]
 [7 0 4]
 [5 0 4]
 [1 3 3]
 [0 9 9]
 [2 9 8]
 [6 9 6]
 [5 5 1]
 [3 5 2]
 [6 3 6]] [1 1 1 0 0 0 0 0 0 0

/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceW


[[2 9 5]
 [0 4 4]
 [4 8 8]
 [8 3 4]
 [5 9 5]
 [8 3 8]
 [0 9 7]
 [5 0 3]
 [8 0 8]
 [1 0 4]] [1 0 1 0 1 0 1 1 0 0] [35.36108956 77.73024202 41.25069183 -4.82735674]
[[7 6 4]
 [2 5 9]
 [2 6 0]
 [0 3 8]
 [0 9 4]
 [6 3 7]
 [8 8 9]
 [1 4 8]
 [1 8 9]
 [9 2 8]
 [9 1 2]
 [5 6 3]
 [3 9 3]
 [7 9 8]
 [4 8 2]
 [8 9 5]
 [8 4 9]
 [7 6 0]
 [5 4 5]
 [6 9 8]] [1 1 0 0 1 1 0 1 1 0 1 0 1 1 1 1 0 0 1 0] [-14.5433811  146.33549235  40.84186436  -4.91655361]
[[2 9 5]
 [0 4 4]
 [4 8 8]
 [8 3 4]
 [5 9 5]
 [8 3 8]
 [0 9 7]
 [5 0 3]
 [8 0 8]
 [1 0 4]] [1 0 1 0 1 0 1 1 0 0] [ -4.44439423  55.14146895 -38.46808391 -15.02498795]
[[7 6 4]
 [2 5 9]
 [2 6 0]
 [0 3 8]
 [0 9 4]
 [6 3 7]
 [8 8 9]
 [1 4 8]
 [1 8 9]
 [9 2 8]
 [9 1 2]
 [5 6 3]
 [3 9 3]
 [7 9 8]
 [4 8 2]
 [8 9 5]
 [8 4 9]
 [7 6 0]
 [5 4 5]
 [6 9 8]] [1 1 0 0 1 1 0 1 1 0 1 0 1 1 1 1 0 0 1 0] [ 45.15366716 104.1489866   21.37798233  -5.13398669]
[[2 9 5]
 [0 4 4]
 [4 8 8]
 [8 3 4]
 [5 9 5]
 [8 3 8]
 [0 9 7]
 [5 0 3]
 [8 0 8]
 [1 0 4]] [1 0 1 0 1 0 1 1 0 0] [-

/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceW

 [1 0 1 1 0 1 0 0 1 1] [ 96.47792213   3.87135857 -41.50992204  20.72264583]
[[3 1 4]
 [6 1 5]
 [6 2 6]
 [7 0 4]
 [0 9 4]
 [6 7 9]
 [1 5 9]
 [4 2 1]
 [8 7 7]
 [5 9 9]
 [0 1 1]
 [5 5 4]
 [3 7 3]
 [4 7 3]
 [8 9 8]
 [1 5 0]
 [1 0 9]
 [0 5 4]
 [2 0 8]
 [1 4 3]] [1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1 0 0] [135.16495957 -95.27503745   8.45548849  10.76228937]
[[1 2 5]
 [4 4 6]
 [3 6 8]
 [5 0 8]
 [4 5 6]
 [5 2 8]
 [5 3 1]
 [0 9 5]
 [7 9 7]
 [8 3 2]] [1 0 1 1 0 1 0 0 1 1] [152.13915075 -14.89672464  -1.5240108   30.60438134]
[[3 1 4]
 [6 1 5]
 [6 2 6]
 [7 0 4]
 [0 9 4]
 [6 7 9]
 [1 5 9]
 [4 2 1]
 [8 7 7]
 [5 9 9]
 [0 1 1]
 [5 5 4]
 [3 7 3]
 [4 7 3]
 [8 9 8]
 [1 5 0]
 [1 0 9]
 [0 5 4]
 [2 0 8]
 [1 4 3]] [1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1 0 0] [ 51.52330188 -74.21390279 -51.0629205   10.72339031]
[[1 2 5]
 [4 4 6]
 [3 6 8]
 [5 0 8]
 [4 5 6]
 [5 2 8]
 [5 3 1]
 [0 9 5]
 [7 9 7]
 [8 3 2]] [1 0 1 1 0 1 0 0 1 1] [  89.76622039  -62.9437575  -187.45030185   10.94874902]
[[3 1 4]
 [6 1 5]
 [6 2 6]
 [7 

/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceW


[[2 9 5]
 [0 4 4]
 [4 8 8]
 [8 3 4]
 [5 9 5]
 [8 3 8]
 [0 9 7]
 [5 0 3]
 [8 0 8]
 [1 0 4]] [1 0 1 0 1 0 1 1 0 0] [ -2.50844113 123.9994428   47.82701076  12.97727284]
[[7 6 4]
 [2 5 9]
 [2 6 0]
 [0 3 8]
 [0 9 4]
 [6 3 7]
 [8 8 9]
 [1 4 8]
 [1 8 9]
 [9 2 8]
 [9 1 2]
 [5 6 3]
 [3 9 3]
 [7 9 8]
 [4 8 2]
 [8 9 5]
 [8 4 9]
 [7 6 0]
 [5 4 5]
 [6 9 8]] [1 1 0 0 1 1 0 1 1 0 1 0 1 1 1 1 0 0 1 0] [-81.77000267  53.39488935 -71.57662662  -6.92330349]
[[2 9 5]
 [0 4 4]
 [4 8 8]
 [8 3 4]
 [5 9 5]
 [8 3 8]
 [0 9 7]
 [5 0 3]
 [8 0 8]
 [1 0 4]] [1 0 1 0 1 0 1 1 0 0] [-21.28383971  81.78753137  47.59072621  -6.9717273 ]
[[7 6 4]
 [2 5 9]
 [2 6 0]
 [0 3 8]
 [0 9 4]
 [6 3 7]
 [8 8 9]
 [1 4 8]
 [1 8 9]
 [9 2 8]
 [9 1 2]
 [5 6 3]
 [3 9 3]
 [7 9 8]
 [4 8 2]
 [8 9 5]
 [8 4 9]
 [7 6 0]
 [5 4 5]
 [6 9 8]] [1 1 0 0 1 1 0 1 1 0 1 0 1 1 1 1 0 0 1 0] [-50.8053081  100.79855682  66.94066946  -7.06068703]
[[2 9 5]
 [0 4 4]
 [4 8 8]
 [8 3 4]
 [5 9 5]
 [8 3 8]
 [0 9 7]
 [5 0 3]
 [8 0 8]
 [1 0 4]] [1 0 1 0 1 0 1 1 0 0

/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/Users/yuxuanzhao/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceW